// client/src/components/Pagination.jsx
import React, { useMemo } from 'react';
import { classNames } from '../utilities/classNames';

// Common reference to unicode character '…' to check against later
const ellipsis = 'ellipsis';

/**
 * Helper method for creating a range of numbers
 * range(1, 5) => [1, 2, 3, 4, 5]
 */
function range(from, to, step = 1) {
  let i = from;
  const range = [];

  while (i <= to) {
    range.push(i);
    i += step;
  }

  return range;
}

function calculatePageNumbers(currentPage = 1, totalPages = 1, pageSiblings = 1) {

  // full case: < 1 ... 4 5 [6] 7 8 ... 10 >
  // case: 1 ... 47 48 [96] 97 98 ... 100
  // case: 1 ... 47 48 [97] 98 99 100

  const startPage = Math.max(2, currentPage - pageSiblings);
  const endPage = Math.min(totalPages - 1, currentPage + pageSiblings);

  const hasLeftDots = startPage > 2;
  // show right dots if we are further than 1 page before the end
  const hasRightDots = endPage < totalPages - 1;

  // If the number of pages is less than the page numbers we want to show in our

  // Cases:
  // 1. Total page count is less than the page pills we want to show: 1 [2] 3
  // 2. Right dots are visible 1 2 [3] 4 ... 10
  // 4. Left dots are visible 1 ... 47 48 [49] 50 51 ... 100

  // first page + last page + current page + 2 * page siblings + previous and next page controls
  const totalPagePills = (2 * pageSiblings) + 5;

  // case: the number of total pages is less than the page pills we want to show in our navigation
  if (totalPages < totalPagePills) {
    const pages = range(1, totalPages);

    return pages;
  }

  // case: 1 ... 46 47 [48] 49 50
  if (hasLeftDots && !hasRightDots) {
    const middlePages = range(startPage, endPage);
    const pages = [1, ellipsis, ...middlePages, totalPages];

    return pages;
  }

  // case: 1 2 3 [4] 5 6 ... 50
  if (!hasLeftDots && hasRightDots) {
    const middlePages = range(startPage, endPage);
    const pages = [1, ...middlePages, ellipsis, totalPages];

    return pages;
  }

  // case: 1 ... 47 48 [49] 50 51 ... 100
  if (hasLeftDots && hasRightDots) {
    const middlePages = range(startPage, endPage);
    const pages = [1, ellipsis, ...middlePages, ellipsis, totalPages];

    return pages;
  }
}

function Pagination({currentPage, totalPages, pageSiblings, handleChangePage}) {
  function handleMoveLeft() {
    handleChangePage(currentPage - 1);
  };

  function handleMoveRight() {
    handleChangePage(currentPage + 1);
  }

  const pageNumbers = useMemo(
    () => calculatePageNumbers(currentPage, totalPages, pageSiblings),
    [currentPage, totalPages, pageSiblings],
  );

  const lastPage = pageNumbers[pageNumbers.length - 1];

  return (
    <nav aria-label="Page navigation">
      <ul className="pagination">

        {/* Previous page button */}
        <li
          className={classNames(['page-item', {
            'disabled': currentPage === 1
          }])}
        >
            <button className="page-link" onClick={handleMoveLeft} disabled={currentPage === 1}>Previous</button>
        </li>

        {/* Show page numbers */}
        {pageNumbers.map((page, index) => {
          const isCurrentPage = currentPage === page;

          // Render ellipsis '…' unicode character
          if (page === ellipsis) {
            return (
              <li key={index} className="page-item" aria-label="More">
                <span className="page-link" aria-hidden="true">&#8230;</span>
              </li>
            );
          }

          return (
            <li key={index}
              className={classNames(['page-item', {
                'active': isCurrentPage
              }])}
              // Conditionally add ARIA attribute
              aria-current={isCurrentPage ? 'true' : undefined}
            >
              <button className="page-link" onClick={() => handleChangePage(page)}>
                {page}
              </button>
            </li>
          );
        })}

        {/* Next page button */}
        <li
          className={classNames(['page-item', {
            'disabled': currentPage === lastPage
          }])}
        >
          <button className="page-link" onClick={handleMoveRight} disabled={currentPage === lastPage}>Next</button>
        </li>
      </ul>
    </nav>
  );
}

export { Pagination };

// client-angular/src/app/shared/components/pagination/pagination.component.ts
import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges } from '@angular/core';
import { range } from '../../utilities/utilities';
import { NgClass } from '@angular/common';

@Component({
  selector: 'app-pagination',
  standalone: true,
  imports: [NgClass],
  templateUrl: './pagination.component.html',
  styleUrl: './pagination.component.scss'
})
export class PaginationComponent implements OnInit, OnChanges {
  @Input() currentPage = 1;
  @Input() totalPages = 1;
  @Input() pageSiblings = 2;
  @Input() visiblePages = 5;
  @Output() pageChange = new EventEmitter<number>();

  // By default, page navigation is displayed as: < [1] >.
  pages: number[] = [1];

  ngOnInit() {
    this.pages = this.calculatePageNumbers(this.currentPage, this.totalPages, this.pageSiblings, this.visiblePages);
  }

  ngOnChanges(_: SimpleChanges) {
    this.pages = this.calculatePageNumbers(this.currentPage, this.totalPages, this.pageSiblings, this.visiblePages);
  }

  handlePageChange(pageNumber: number, event: Event) {
    // Prevent reloading the page.
    event.preventDefault();

    this.currentPage = pageNumber;
    this.pages = this.calculatePageNumbers(this.currentPage, this.totalPages, this.pageSiblings, this.visiblePages);
    this.pageChange.emit(pageNumber);
  }

  handleMoveLeft(event: Event) {
    this.handlePageChange(this.currentPage - 1, event);
  }

  handleMoveRight(event: Event) {
    this.handlePageChange(this.currentPage + 1, event);
  }

  private calculatePageNumbers(currentPage: number, totalPages: number, pageSiblings: number, visiblePages: number): number[] {
    // Ensure a fixed total number of pages (e.g. 5 pages) is always shown.
    // Center the current page within the range when possible.
    // Show more pages on one side of the current page, when the current page is near the beginning or end.

    let startPage;
    let endPage;

    if (totalPages <= visiblePages) {
      // If total pages less than visible pages, show all pages.
      startPage = 1;
      endPage = totalPages;
    } else if (currentPage <= pageSiblings) {
      // If closer to the beginning.
      // Display: 1 [2] 3 4 5.
      startPage = 1;
      endPage = visiblePages;
    } else if (currentPage + pageSiblings >= totalPages) {
      // If closer to the end.
      // Display: 6 7 8 [9] 10
      startPage = totalPages - visiblePages + 1;
      endPage = totalPages;
    } else {
      // Current page is centered.
      // Display: 3 4 [5] 6 7
      startPage = currentPage - pageSiblings;
      endPage = currentPage + pageSiblings;
    }

    const pages = range(startPage, endPage);

    return pages;
  }
}

<nav aria-label="Page navigation">
  <ul class="pagination">
    <li class="page-item" [class.disabled]="(currentPage === 1) || disabled" aria-label="First">
      <a class="page-link" href (click)="handlePageChange(1, $event)" aria-hidden="true">&laquo;&laquo;</a>
    </li>
    <li class="page-item" [class.disabled]="(currentPage === 1) || disabled">
      <a class="page-link" href (click)="handleMoveLeft($event)">Previous</a>
    </li>
    @for (page of pages; track $index) {
      <li class="page-item" [class.active]="(currentPage === page)" [class.disabled]="(currentPage !== page) && disabled" [attr.aria-current]="currentPage === page ? 'page' : null">
        <a class="page-link" href (click)="handlePageChange(page, $event)">{{ page }}</a>
      </li>
    }
    <li class="page-item" [class.disabled]="(currentPage === totalPages) || disabled">
      <a class="page-link" href (click)="handleMoveRight($event)">Next</a>
    </li>
    <li class="page-item" [class.disabled]="(currentPage === totalPages) || disabled" aria-label="Last">
      <a class="page-link" href (click)="handlePageChange(totalPages, $event)" aria-hidden="true">&raquo;&raquo;</a>
    </li>
  </ul>
</nav>
